export const FAVORITES_LIST_REQUEST = 'FAVORITES_REQUEST'
export const FAVORITES_LIST_SUCCESS = 'FAVORITES_LIST_SUCCESS'
export const FAVORITES_LIST_FAIL = 'FAVORITES_LIST_FAIL'
export const FAVORITES_LIST_CLEAR = 'FAVORITES_LIST_CLEAR'